services:
  order-postgres:
    image: postgres:15
    container_name: order-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${ORDER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDER_POSTGRES_DB}
    ports:
      - "${ORDER_POSTGRES_PORT}:5432"
    volumes:
      - order-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDER_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - rocket-shop-network

networks:
  rocket-shop-network:
    external: true

volumes:
  order-pgdata:
