services:
  inventory-mongodb:
    image: ${INVENTORY_MONGO_IMAGE}
    container_name: inventory-mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${INVENTORY_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${INVENTORY_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${INVENTORY_MONGO_DB}
    ports:
      - "${INVENTORY_MONGO_PORT}:27017"
    volumes:
      - inventory-mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - rocket-shop-network

networks:
  rocket-shop-network:
    external: true

volumes:
  inventory-mongodata:
